import type { Metadata } from "next";
import "./globals.css";

import { NavBar } from "@/components/layout/navbar";
import FooterApp from "@/components/layout/footer";
import { ConfigProvider } from "antd";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/images/cover.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <NavBar />
        {children}
        <FooterApp />
      </body>
    </html>
  );
}
