import type { Metadata } from "next";
import "./globals.css";

import { NavBar } from "@/components/layout/navbar";
import FooterApp from "@/components/layout/footer";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/images/cover.png'
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()


  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <SessionProvider>
          <NavBar session={session} />
          {children}
          <FooterApp />
        </SessionProvider>


      </body>
    </html>
  );
}
